
package Interfaz;

import EstructurasdeDatos.Almacen;
import EstructurasdeDatos.ListaAlmacen;
import EstructurasdeDatos.ListaObjetos;
import EstructurasdeDatos.Objeto;
import Grafos.ColoreadoGrafos;
import Grafos.Arista;
import Grafos.Grafica;
import Grafos.Grafo;
import Grafos.ListaAristas;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {
    JFileChooser archivo= new JFileChooser();
    Grafica grafica= new Grafica();
    ColoreadoGrafos pintar= new ColoreadoGrafos();
    int NumVertices= 5;
    int[][] arreglo= new int[NumVertices][NumVertices];
    ListaAristas arista= new ListaAristas();
    ListaAlmacen lista_almacenes= new ListaAlmacen();
    Grafo grafo= new Grafo(NumVertices, arreglo, "Almacen", lista_almacenes, arista);
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        CrearArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Input1 = new javax.swing.JTextArea();
        CargarArchivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Input2 = new javax.swing.JTextArea();
        ModificarArchivo = new javax.swing.JButton();
        GenerarGrafo = new javax.swing.JButton();
        MostrarMatrizAdyacencia = new javax.swing.JButton();
        MostrarGrafo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Input3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Input4 = new javax.swing.JTextArea();
        AgregarAlmacen = new javax.swing.JButton();
        Subtitulo1 = new javax.swing.JLabel();
        Subtitulo2 = new javax.swing.JLabel();
        Subtitulo3 = new javax.swing.JLabel();
        Subtitulo4 = new javax.swing.JLabel();
        Subtitulo5 = new javax.swing.JLabel();
        Subtitulo6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Input5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Input6 = new javax.swing.JTextArea();
        AgregarCamino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        Titulo.setText("Amazon Organized Chaos");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        CrearArchivo.setText("Crear Archivo");
        CrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CrearArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Input1.setColumns(20);
        Input1.setRows(5);
        Input1.setText("Ingrese la información que se va a guardar en el archivo txt:");
        jScrollPane1.setViewportView(Input1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, 60));

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        Input2.setColumns(20);
        Input2.setRows(5);
        Input2.setText("Ingrese la información que desea modificar en el archivo txt: ");
        jScrollPane2.setViewportView(Input2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, 60));

        ModificarArchivo.setText("Modificar Archivo");
        ModificarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        GenerarGrafo.setText("Generar Grafo");
        GenerarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(GenerarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        MostrarMatrizAdyacencia.setText("Mostrar Matriz Adyacencia");
        MostrarMatrizAdyacencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarMatrizAdyacenciaActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarMatrizAdyacencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        MostrarGrafo.setText("Mostrar Grafo");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        Input3.setColumns(20);
        Input3.setRows(5);
        Input3.setText("Ingrese el número del almacen al que conectará el nuevo almacen: ");
        jScrollPane3.setViewportView(Input3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 60));

        Input4.setColumns(20);
        Input4.setRows(5);
        Input4.setText("Ingrese 1 para agregar un nuevo almacen: ");
        jScrollPane4.setViewportView(Input4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 60));

        AgregarAlmacen.setText("Agregar Almacen");
        AgregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAlmacenActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        Subtitulo1.setText("Números de los Almacenes Precargados");
        getContentPane().add(Subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        Subtitulo2.setText("Almacen 1: 0");
        getContentPane().add(Subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        Subtitulo3.setText("Almacen 2: 1");
        getContentPane().add(Subtitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        Subtitulo4.setText("Almacen 3: 2");
        getContentPane().add(Subtitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        Subtitulo5.setText("Almacen 4: 3");
        getContentPane().add(Subtitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        Subtitulo6.setText("Almacen 5: 4");
        getContentPane().add(Subtitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        Input5.setColumns(20);
        Input5.setRows(5);
        Input5.setText("Ingrese el número del almacen origen: ");
        jScrollPane5.setViewportView(Input5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 150, 60));

        Input6.setColumns(20);
        Input6.setRows(5);
        Input6.setText("Ingrese el número del almacen destino: ");
        jScrollPane6.setViewportView(Input6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 160, 60));

        AgregarCamino.setText("Agregar Camino");
        AgregarCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCaminoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArchivoActionPerformed
        try{
            FileWriter file= new FileWriter("C:/Users/Juan Ceballos/Documents/NetBeansProjects/Proyecto1.JuanCeballos.ChristianCusato.JesusMatcha/src/test/java/Inventario.txt");
            file.close();
            JOptionPane.showMessageDialog(null, "Se creó el archivo exitosamente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor, intentelo de nuevo");
        }
    }//GEN-LAST:event_CrearArchivoActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        try{
           if((Input1.getText().isEmpty()|| Input1.getText().isBlank())){
             JOptionPane.showMessageDialog(null, "El área de texto no puede estar vacío. ");
        }else{
              try{
                String nombre="";
                javax.swing.JFileChooser file=new javax.swing.JFileChooser();
                file.showSaveDialog(this);
                File guardar =file.getSelectedFile();

            if(guardar !=null){
             /*guardamos el archivo y le damos el formato directamente,
              * si queremos que se guarde en formato doc lo definimos como .doc*/
              FileWriter salvar=new FileWriter(guardar+".txt");
              salvar.write(Input1.getText());
              salvar.close();
              JOptionPane.showMessageDialog(null,"El archivo se ha guardado exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
              }
           }catch(IOException ex){
             JOptionPane.showMessageDialog(null,"Su archivo no se ha guardado","Advertencia",JOptionPane.WARNING_MESSAGE);
            }
           } 
               
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor inténtelo de nuevo");

        }
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void ModificarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarArchivoActionPerformed
         try {
            if((Input2.getText().isEmpty()|| Input2.getText().isBlank())){
             JOptionPane.showMessageDialog(null, "El área de texto no puede estar vacío. ");
        }else{
            BufferedWriter bw = new BufferedWriter(new FileWriter("C:/Users/Juan Ceballos/Documents/NetBeansProjects/Proyecto1.JuanCeballos.ChristianCusato.JesusMatcha/src/test/java/Inventario.txt"));
            bw.write(Input2.getText());
            bw.close();
            JOptionPane.showMessageDialog(null, "Se modificó el archivo exitosamente");
            }
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModificarArchivoActionPerformed

    private void GenerarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarGrafoActionPerformed
         try{
            Objeto objeto1AlmacenA= new Objeto("Pantalla", 3);
            Objeto objeto2AlmacenA= new Objeto("RAM", 2);
            Objeto objeto3AlmacenA= new Objeto("Procesador", 1);
            ListaObjetos listaObjetosAlmacenA= new ListaObjetos();
            listaObjetosAlmacenA.insertFinal(objeto1AlmacenA);
            listaObjetosAlmacenA.insertFinal(objeto2AlmacenA);
            listaObjetosAlmacenA.insertFinal(objeto3AlmacenA);
            Almacen AlmacenA= new Almacen("Almacen A", listaObjetosAlmacenA);
            Objeto objeto1AlmacenB= new Objeto("Pantalla", 3);
            Objeto objeto2AlmacenB= new Objeto("Grafica", 5);
            ListaObjetos listaObjetosAlmacenB= new ListaObjetos();
            listaObjetosAlmacenB.insertFinal(objeto1AlmacenB);
            listaObjetosAlmacenB.insertFinal(objeto2AlmacenB);
            Almacen AlmacenB= new Almacen("Almacen B", listaObjetosAlmacenB);
            Objeto objeto1AlmacenC= new Objeto("Placa", 7);
            Objeto objeto2AlmacenC= new Objeto("Teclado", 8);
            ListaObjetos listaObjetosAlmacenC= new ListaObjetos();
            listaObjetosAlmacenC.insertFinal(objeto1AlmacenC);
            listaObjetosAlmacenC.insertFinal(objeto2AlmacenC);
            Almacen AlmacenC= new Almacen("Almacen C", listaObjetosAlmacenC);
            Objeto objeto1AlmacenD= new Objeto("Mouse", 2);
            ListaObjetos listaObjetosAlmacenD= new ListaObjetos();
            listaObjetosAlmacenD.insertFinal(objeto1AlmacenD);
            Almacen AlmacenD= new Almacen("Almacen d", listaObjetosAlmacenD);
            Objeto objeto1AlmacenE= new Objeto("Microfono", 7);
            Objeto objeto2AlmacenE= new Objeto("Audifonos", 10);
            ListaObjetos listaObjetosAlmacenE= new ListaObjetos();
            listaObjetosAlmacenE.insertFinal(objeto1AlmacenE);
            listaObjetosAlmacenE.insertFinal(objeto2AlmacenE);
            Almacen AlmacenE= new Almacen("Almacen E", listaObjetosAlmacenE);
            lista_almacenes.insertFinal(AlmacenA);
            lista_almacenes.insertFinal(AlmacenB);
            lista_almacenes.insertFinal(AlmacenC);
            lista_almacenes.insertFinal(AlmacenD);
            lista_almacenes.insertFinal(AlmacenE);
            Arista arista1= new Arista(AlmacenA, AlmacenB, 10);
            Arista arista2= new Arista(AlmacenA, AlmacenC, 20);
            Arista arista3= new Arista(AlmacenB, AlmacenC, 5);
            Arista arista4= new Arista(AlmacenB, AlmacenD, 8);
            Arista arista5= new Arista(AlmacenC, AlmacenD, 4);
            Arista arista6= new Arista(AlmacenC, AlmacenE, 13);
            Arista arista7= new Arista(AlmacenD, AlmacenE, 3);
            Arista arista8= new Arista(AlmacenE, AlmacenA, 25);
            arista.insertFinal(arista1);
            arista.insertFinal(arista2);
            arista.insertFinal(arista3);
            arista.insertFinal(arista4);
            arista.insertFinal(arista5);
            arista.insertFinal(arista6);
            arista.insertFinal(arista7);
            arista.insertFinal(arista8);
            grafo.LlenarMatriz(0, 1, 1);
            grafo.LlenarMatriz(0, 2, 1);
            grafo.LlenarMatriz(1, 2, 1);
            grafo.LlenarMatriz(1, 3, 1);
            grafo.LlenarMatriz(2, 3, 1);
            grafo.LlenarMatriz(2, 4, 1);
            grafo.LlenarMatriz(3, 4, 1);
            grafo.LlenarMatriz(4, 0, 1);
            JOptionPane.showMessageDialog(null, "Se ha generado el grafo exitosamente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor intentelo de nuevo");
        }
    }//GEN-LAST:event_GenerarGrafoActionPerformed

    private void MostrarMatrizAdyacenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarMatrizAdyacenciaActionPerformed
        try{
            grafo.ImprimirMatriz();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor, intentelo de nuevo");
        }
    }//GEN-LAST:event_MostrarMatrizAdyacenciaActionPerformed

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        try{
            pintar.mColorear(1);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, por favor, intentelo de nuevo");
        }
    }//GEN-LAST:event_MostrarGrafoActionPerformed

    private void AgregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlmacenActionPerformed
        try {
            if((Input3.getText().isEmpty()|| Input3.getText().isBlank()) && (Input4.getText().isEmpty()|| Input4.getText().isBlank())){
             JOptionPane.showMessageDialog(null, "Las áreas de texto no puede estar vacías. ");
        }else{
            grafo.LlenarMatriz( Integer.parseInt(Input4.getText()), Integer.parseInt(Input3.getText()), 1);
            JOptionPane.showMessageDialog(null, "Se agregó el almacen exitosamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, por favor, inténtelo de nuevo");
        }
    }//GEN-LAST:event_AgregarAlmacenActionPerformed

    private void AgregarCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCaminoActionPerformed
        try {
            if((Input5.getText().isEmpty()|| Input5.getText().isBlank()) && (Input6.getText().isEmpty()|| Input6.getText().isBlank())){
             JOptionPane.showMessageDialog(null, "Las áreas de texto no puede estar vacías. ");
        }else{
            grafo.LlenarMatriz(Integer.parseInt(Input5.getText()), Integer.parseInt(Input6.getText()), 1);
            JOptionPane.showMessageDialog(null, "Se creo el nuevo camino exitosamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, por favor, inténtelo de nuevo");
        }
    }//GEN-LAST:event_AgregarCaminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAlmacen;
    private javax.swing.JButton AgregarCamino;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton CrearArchivo;
    private javax.swing.JButton GenerarGrafo;
    private javax.swing.JTextArea Input1;
    private javax.swing.JTextArea Input2;
    private javax.swing.JTextArea Input3;
    private javax.swing.JTextArea Input4;
    private javax.swing.JTextArea Input5;
    private javax.swing.JTextArea Input6;
    private javax.swing.JButton ModificarArchivo;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton MostrarMatrizAdyacencia;
    private javax.swing.JLabel Subtitulo1;
    private javax.swing.JLabel Subtitulo2;
    private javax.swing.JLabel Subtitulo3;
    private javax.swing.JLabel Subtitulo4;
    private javax.swing.JLabel Subtitulo5;
    private javax.swing.JLabel Subtitulo6;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
